bs

diff --git a/bin/load_path b/bin/load_path
--- a/bin/load_path
+++ b/bin/load_path
@@ -1,30 +1,36 @@
 #!/bin/sh
 
-load_path() {
-  file="$1"
+if [ "$(type -t load_path)" != "function" ]; then
+  load_path() {
+    file="$1"
 
-  if [ ! -f "$file" ]; then
-    return 1
-  fi
-
-  while read -r p; do
-    case "$p" in
-      # Skip empty lines
-      "") continue ;;
-      # Ignore comments
-      \#*) continue ;;
-      # Strip end of line comments
-      *\ \#*) p="${p% #*}" ;;
-      # Simulate home expansion
-      \~/*) p="$HOME/${p#\~/}" ;;
-    esac
-    if [ -d "$p" ]; then
-      source "$HOME/bin/pathmunge" "$p" after
-    else # TODO: indicate line number
-      echo >&2 "$p: invalid directory found in $file"
+    if [ ! -f "$file" ]; then
+      return 1
     fi
-  done <"$file"
-  unset file
-}
 
-[ "${SHLVL:-0}" -eq 1 ] && load_path "$@"
+    while read -r p; do
+      case "$p" in
+        # Skip empty lines
+        "") continue ;;
+        # Ignore comments
+        \#*) continue ;;
+        # Strip end of line comments
+        *\ \#*) p="${p% #*}" ;;
+        # Simulate home expansion
+        \~/*) p="$HOME/${p#\~/}" ;;
+      esac
+      if [ -d "$p" ]; then
+        # shellcheck disable=SC1090
+        . "$HOME/bin/pathmunge" "$p" after
+      else # TODO: indicate line number
+        echo >&2 "$p: invalid directory found in $file"
+      fi
+    done <"$file"
+    unset file
+  }
+fi
+
+# In POSIX sh, BASH_SOURCE is undefined
+# but this still works on macOS (sh linked to bash?)
+# shellcheck disable=SC2128
+[ "$0" = "$BASH_SOURCE" ] && load_path "$@"
diff --git a/bin/rdiff b/bin/rdiff
--- a/bin/rdiff
+++ b/bin/rdiff
@@ -2,31 +2,34 @@
 
 # Reverse diff: compare 2 files and output common lines
 
-log() {
-  printf "%s\n" "$@"
-}
+if [ "$(type -t rdiff)" != "function" ]; then
+  rdiff() {
+    if [[ $# -eq 0 ]]; then
+      log "usage: ${0##*/} file1 file2"
+    elif [[ $# -ne 2 ]] || [[ -z "$1" ]] || [[ -z "$2" ]]; then
+      error "invalid arguments"
+      # elif ! exists "$1" then;
+      #   error "$1: no such file"
+      # elif ! exists "$2" then;
+      #   error "$2: no such file"
+    else
+      comm -1 -2 <(sort "$1") <(sort "$2")
+    fi # grep -F -x -f ?
+  }
 
-error() {
-  log >&2 "${0##*/}: $*"
-  return 1
-}
+  log() {
+    printf "%s\n" "$@"
+  }
 
-exists() {
-  [[ -f "$1" ]] && [[ -L "$1" ]]
-}
+  error() {
+    log >&2 "${0##*/}: $*"
+    return 1
+  }
 
-main() {
-  if [[ $# -eq 0 ]]; then
-    log "usage: ${0##*/} file1 file2"
-  elif [[ $# -ne 2 ]] || [[ -z "$1" ]] || [[ -z "$2" ]]; then
-    error "invalid arguments"
-    # elif ! exists "$1" then;
-    #   error "$1: no such file"
-    # elif ! exists "$2" then;
-    #   error "$2: no such file"
-  else
-    comm -1 -2 <(sort "$1") <(sort "$2")
-  fi # grep -F -x -f ?
-}
+  # exists() {
+  #   [[ -f "$1" ]] && [[ -L "$1" ]]
+  # }
+fi
 
-[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
+# shellcheck disable=SC2128
+[[ "$0" == "$BASH_SOURCE" ]] && rdiff "$@"
