path

diff --git a/bin/load_path b/bin/load_path
--- a/bin/load_path
+++ b/bin/load_path
@@ -1,31 +1,30 @@
 #!/bin/sh
 
-# if ! hash load_path 2>/dev/null; then
-#   load_path() {
-file="$1"
+load_path() {
+  file="$1"
 
-if [ ! -f "$file" ]; then
-  return 1
-fi
-
-while read -r p; do
-  case "$p" in
-    # Skip empty lines
-    "") continue ;;
-    # Ignore comments
-    \#*) continue ;;
-    # Strip end of line comments
-    *\ \#*) p="${p% #*}" ;;
-    # Simulate home expansion
-    \~/*) p="$HOME/${p#\~/}" ;;
-  esac
-  if [ -d "$p" ]; then
-    pathmunge "$p" after
-  else # TODO: indicate line number
-    echo >&2 "$p: invalid directory found in $file"
+  if [ ! -f "$file" ]; then
+    return 1
   fi
-done <"$file"
-# }
-# fi
 
-# load_path "$@"
+  while read -r p; do
+    case "$p" in
+      # Skip empty lines
+      "") continue ;;
+      # Ignore comments
+      \#*) continue ;;
+      # Strip end of line comments
+      *\ \#*) p="${p% #*}" ;;
+      # Simulate home expansion
+      \~/*) p="$HOME/${p#\~/}" ;;
+    esac
+    if [ -d "$p" ]; then
+      source "$HOME/bin/pathmunge" "$p" after
+    else # TODO: indicate line number
+      echo >&2 "$p: invalid directory found in $file"
+    fi
+  done <"$file"
+  unset file
+}
+
+load_path "$@"
